# Generated by Django 2.2.4 on 2019-08-12 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Symbols', models.CharField(max_length=25)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Current_Price', models.CharField(max_length=10)),
                ('Percentage_Change', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Company_Name',
        ),
    ]
