# Generated by Django 2.2.4 on 2019-08-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190812_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Current_Price',
        ),
        migrations.RemoveField(
            model_name='company',
            name='Percentage_Change',
        ),
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
    ]
